Jenkins installation aborts due to failure in disk-usage plugin
cf. https://issues.jenkins-ci.org/browse/JENKINS-47546 - watching this

SEVERE: Timer task hudson.plugins.disk_usage.WorkspaceDiskUsageCalculationThread@634bd4b3 failed
java.lang.ClassCastException: jenkins.security.ImpersonatingScheduledExecutorService cannot be cast to java.util.concurrent.ScheduledThreadPoolExecutor